const baseStyles = `
  * { box-sizing: border-box; }
  html { background: #0b0d10; color: #e8eaed; font-family: Inter, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; }
  body { margin: 0; }
  button, input { font: inherit; }
`;

export function getLoginPage(nonce: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hivelet Access</title><style nonce="${nonce}">${baseStyles}
body{display:grid;place-items:center;min-height:100vh;padding:24px;background:radial-gradient(circle at 50% -15%,#29231e 0,#121316 34%,#0b0d10 62%)}
.login{width:min(440px,100%);padding:10px;border:1px solid #2b3038;border-radius:24px;background:#111318cc;box-shadow:0 30px 90px #0009;backdrop-filter:blur(20px)}.inner{padding:28px 28px 18px;border:1px solid #292e36;border-radius:17px;background:linear-gradient(145deg,#191c21,#121418)}
.brand{display:flex;align-items:center;justify-content:space-between;font-size:13px;font-weight:650}.brand-name{display:flex;align-items:center;gap:10px}.brand i{width:10px;height:10px;border-radius:3px;background:#f28b25;box-shadow:0 0 18px #f28b2588}.secure{display:flex;align-items:center;gap:6px;color:#747c87;font:600 9px/1 ui-monospace,Consolas,monospace;text-transform:uppercase;letter-spacing:.08em}.secure:before{content:'';width:6px;height:6px;border-radius:50%;background:#67c587}
.kicker{margin:54px 0 9px;color:#f28b25;font-size:10px;font-weight:700;letter-spacing:.13em;text-transform:uppercase}h1{margin:0;font-size:36px;letter-spacing:-.05em;font-weight:550}.lede{margin:11px 0 30px;color:#858d98;font-size:13px;line-height:1.55}
label{display:block;margin-bottom:8px;color:#a2a8b0;font-size:11px;font-weight:600}input,button{width:100%;height:48px;border-radius:10px}input{padding:0 14px;border:1px solid #343a43;background:#0d0f12;color:#f2f4f7;outline:none;transition:border-color .15s,box-shadow .15s}input:focus{border-color:#f28b25;box-shadow:0 0 0 3px #f28b2522}
button{margin-top:10px;border:0;background:#f28b25;color:#17110b;font-size:12px;font-weight:750;cursor:pointer;transition:background .15s,transform .15s}button:hover{background:#ffa044;transform:translateY(-1px)}button:focus-visible{outline:2px solid #fff;outline-offset:2px}button:disabled{opacity:.45;transform:none}.error{min-height:18px;margin:13px 0 0;color:#ff7b72;font-size:12px}.footer{display:flex;align-items:center;justify-content:space-between;padding:14px 18px 5px;color:#69717d;font-size:10px}.footer a{color:#a8afb8;text-decoration:none}.footer a:hover,.footer a:focus-visible{color:#f2f4f7;outline:0}
</style></head><body><main class="login"><section class="inner"><div class="brand"><span class="brand-name"><i></i>hivelet</span><span class="secure">local access</span></div><p class="kicker">Runtime observability</p><h1>Sign in to Flow</h1><p class="lede">Inspect live modules, endpoint traffic, latency, and runtime changes from one private workspace.</p><form id="login"><label for="password">One-time dashboard password</label><input id="password" name="password" type="password" autocomplete="current-password" autofocus required><button id="submit" type="submit">Open dashboard</button><p id="error" class="error" role="alert"></p></form></section><footer class="footer"><span>Hivelet Flow</span><a href="https://github.com/hivelet/packages" target="_blank" rel="noreferrer">GitHub ↗</a></footer></main>
<script nonce="${nonce}">const form=document.getElementById('login'),button=document.getElementById('submit'),error=document.getElementById('error');form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;error.textContent='';try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:form.password.value})});if(!response.ok)throw new Error(response.status===429?'Too many attempts. Wait one minute.':'Password is not valid.');location.replace('/')}catch(reason){error.textContent=reason.message;button.disabled=false}})</script></body></html>`;
}

export function getFlowPage(nonce: string, refreshInterval: number): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark">
<title>Hivelet Flow</title><style nonce="${nonce}">${baseStyles}
html,body,#flow{width:100%;height:100%;overflow:hidden}.canvas{position:fixed;inset:0;background:#0b0d10;touch-action:none;cursor:grab}.canvas:active{cursor:grabbing}
.grid{position:absolute;inset:-100%;width:300%;height:300%;background-image:radial-gradient(#343a43 1px,transparent 1px);background-size:24px 24px;opacity:.36;transform-origin:0 0}.world{position:absolute;inset:0;transform-origin:0 0}.edges{position:absolute;inset:0;width:1px;height:1px;overflow:visible;pointer-events:none}
.edge{fill:none;stroke:#3b414b;stroke-width:1.5}.edge.live{stroke:#f28b25;stroke-width:2;stroke-dasharray:5 9;animation:traffic .65s linear infinite}
.node{position:absolute;width:244px;overflow:hidden;border:1px solid #2d333c;border-radius:12px;background:#15181d;color:#e8eaed;box-shadow:0 12px 36px #0005;cursor:move;user-select:none;transition:border-color .14s,box-shadow .14s,transform .14s}
.node:hover,.node.selected{border-color:#69717d;box-shadow:0 16px 42px #0008}.node.module{width:276px;border-color:#4b3b2c;background:linear-gradient(145deg,#201b17,#17191d)}.node.active{border-color:#f28b25;box-shadow:0 0 0 3px #f28b2518,0 16px 42px #0008}
.node-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 14px;border-bottom:1px solid #292e36}.type{display:flex;align-items:center;gap:8px;color:#a8afb8;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.type i{width:7px;height:7px;border-radius:50%;background:#67c587}.module .type i{border-radius:2px;background:#f28b25}.method{padding:4px 7px;border-radius:5px;background:#242a31;color:#b8bec7;font:700 9px/1 ui-monospace,Consolas,monospace}.method.post{color:#70c7ff}.method.patch{color:#d8a9ff}.method.delete{color:#ff8c86}
.node-tags{display:flex;align-items:center;gap:6px}.version{padding:4px 7px;border:1px solid #554231;border-radius:6px;background:#2b2119;color:#f7a95d;font:650 10px/1 ui-monospace,Consolas,monospace}.endpoint-version{border-color:#343a43;background:#20242a;color:#9da5af}.node-title{padding:14px 14px 4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;font-weight:600}.node-subtitle{padding:3px 14px 13px;color:#7f8791;font:10px/1.4 ui-monospace,Consolas,monospace;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.node-meta{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:#292e36}.metric{min-width:0;padding:10px 12px;background:#13161a}.metric span{display:block;color:#747c87;font-size:9px;font-weight:650;letter-spacing:.06em;text-transform:uppercase}.metric b{display:block;margin-top:5px;overflow:hidden;text-overflow:ellipsis;color:#dfe2e6;font:550 15px/1 ui-monospace,Consolas,monospace}.metric b.good{color:#73c991}.metric b.warn{color:#ff9b91}
.hud{position:fixed;z-index:10;top:16px;left:16px;right:16px;display:flex;align-items:flex-start;justify-content:space-between;gap:12px;pointer-events:none}.panel{border:1px solid #2b3038;border-radius:10px;background:#15181de8;box-shadow:0 10px 28px #0004;backdrop-filter:blur(14px);pointer-events:auto}.brand{display:flex;align-items:center;gap:10px;padding:11px 14px;font-size:13px;font-weight:650}.brand-mark{width:9px;height:9px;border-radius:3px;background:#f28b25}.live{display:flex;align-items:center;gap:6px;margin-left:6px;color:#858d98;font-size:9px;font-weight:650;letter-spacing:.08em;text-transform:uppercase}.dot{width:6px;height:6px;border-radius:50%;background:#67c587}
.stats{display:flex}.stat{min-width:91px;padding:9px 12px;border-left:1px solid #292e36}.stat:first-child{border:0}.stat span{display:block;color:#747c87;font-size:8px;font-weight:650;letter-spacing:.07em;text-transform:uppercase}.stat b{display:block;margin-top:5px;font:550 14px/1 ui-monospace,Consolas,monospace}
.tools{position:fixed;z-index:10;left:16px;bottom:16px;display:flex;padding:4px}.tools button{width:36px;height:34px;border:0;border-radius:7px;background:transparent;color:#aab0b8;cursor:pointer}.tools button:hover,.tools button:focus-visible{background:#2a3038;color:#fff;outline:0}.tools .logout:hover{background:#3a2424;color:#ff9b91}
.inspector{position:fixed;z-index:10;right:16px;bottom:16px;width:min(340px,calc(100% - 32px));padding:15px}.inspector[hidden]{display:none}.inspector-label{color:#f28b25;font-size:9px;font-weight:700;letter-spacing:.09em;text-transform:uppercase}.inspector h2{margin:7px 0 14px;overflow:hidden;text-overflow:ellipsis;font-size:17px;font-weight:600;letter-spacing:-.02em}.detail{display:flex;justify-content:space-between;gap:16px;padding:8px 0;border-top:1px solid #292e36;color:#7f8791;font-size:11px}.detail b{overflow:hidden;text-overflow:ellipsis;color:#d9dde2;font-family:ui-monospace,Consolas,monospace;font-weight:500;text-align:right}
.empty{position:fixed;inset:0;display:grid;place-items:center;color:#69717d;font-size:11px}.empty[hidden]{display:none}@keyframes traffic{to{stroke-dashoffset:-14}}
@media(max-width:760px){.hud{top:10px;left:10px;right:10px}.stats .stat:nth-child(-n+2){display:none}.stat{min-width:76px}.tools{left:10px;bottom:10px}.inspector{right:10px;bottom:58px}.node{width:220px}.node.module{width:240px}}
</style></head><body>
<div id="flow" class="canvas"><div id="grid" class="grid"></div><div id="world" class="world"><svg id="edges" class="edges"></svg><div id="nodes"></div></div><div id="empty" class="empty">Waiting for runtime modules</div></div>
<header class="hud"><div class="brand panel"><i class="brand-mark"></i>hivelet <span class="live"><i class="dot"></i><span id="connection">live</span></span></div><div class="stats panel"><div class="stat"><span>Modules</span><b id="modules">0</b></div><div class="stat"><span>Endpoints</span><b id="endpoints">0</b></div><div class="stat"><span>Requests / min</span><b id="rpm">0</b></div><div class="stat"><span>Avg latency</span><b id="latency">0 ms</b></div><div class="stat"><span>Error rate</span><b id="errors">0%</b></div></div></header>
<nav class="tools panel" aria-label="Flow controls"><button id="zoom-in" title="Zoom in">+</button><button id="zoom-out" title="Zoom out">−</button><button id="fit" title="Fit flow">⌂</button><button id="logout" class="logout" title="Sign out">×</button></nav>
<aside id="inspector" class="inspector panel" hidden><span id="inspect-label" class="inspector-label"></span><h2 id="inspect-title"></h2><div id="details"></div></aside>
<script nonce="${nonce}">
const refresh=${refreshInterval},flow=document.getElementById('flow'),world=document.getElementById('world'),grid=document.getElementById('grid'),nodesLayer=document.getElementById('nodes'),edges=document.getElementById('edges');
const state={x:60,y:80,scale:1,nodes:new Map(),snapshot:null,drag:null,pan:null,timer:null,fitted:false};const el=id=>document.getElementById(id),fmt=value=>value<10?value.toFixed(1):Math.round(value),time=value=>new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(value));
function transform(){const value='translate('+state.x+'px,'+state.y+'px) scale('+state.scale+')';world.style.transform=value;grid.style.transform=value}
function positionFor(id,type,index,moduleIndex){const saved=localStorage.getItem('hivelet:flow:'+id);if(saved){try{return JSON.parse(saved)}catch{}}return type==='module'?{x:70,y:moduleIndex*330+70}:{x:430+(index%3)*285,y:moduleIndex*330+20+Math.floor(index/3)*205}}
function moduleHtml(item){return '<div class="node-head"><span class="type"><i></i>module</span><span class="version">v'+escape(item.version)+'</span></div><div class="node-title">'+escape(item.name)+'</div><div class="node-subtitle">loaded '+time(item.loadedAt)+'</div><div class="node-meta"><div class="metric"><span>Endpoints</span><b>'+item.routeCount+'</b></div><div class="metric"><span>Total requests</span><b>'+item.requests+'</b></div><div class="metric"><span>Requests / min</span><b>'+item.requestsPerMinute+'</b></div><div class="metric"><span>Avg latency</span><b>'+fmt(item.averageResponseTime)+' ms</b></div></div>'}
function endpointHtml(item){const method=item.method.toLowerCase(),errorClass=item.errorRate>0?'warn':'good';return '<div class="node-head"><span class="type"><i></i>endpoint</span><span class="node-tags"><span class="version endpoint-version">v'+escape(item.version)+'</span><span class="method '+method+'">'+item.method+'</span></span></div><div class="node-title">'+escape(item.path)+'</div><div class="node-subtitle">'+escape(item.id)+'</div><div class="node-meta"><div class="metric"><span>Requests / min</span><b>'+item.requestsPerMinute+'</b></div><div class="metric"><span>Error rate</span><b class="'+errorClass+'">'+(item.errorRate*100).toFixed(1)+'%</b></div><div class="metric"><span>Average</span><b>'+fmt(item.averageResponseTime)+' ms</b></div><div class="metric"><span>P95 latency</span><b>'+fmt(item.p95ResponseTime)+' ms</b></div></div>'}
function nodeElement(item,type,index,moduleIndex){let record=state.nodes.get(item.key);if(!record){const node=document.createElement('article'),position=positionFor(item.key,type,index,moduleIndex);node.tabIndex=0;node.dataset.key=item.key;record={node,position,item};state.nodes.set(item.key,record);nodesLayer.append(node);node.addEventListener('pointerdown',event=>{event.stopPropagation();node.setPointerCapture(event.pointerId);state.drag={record,startX:event.clientX,startY:event.clientY,x:record.position.x,y:record.position.y}});node.addEventListener('pointermove',event=>{if(!state.drag||state.drag.record!==record)return;record.position.x=state.drag.x+(event.clientX-state.drag.startX)/state.scale;record.position.y=state.drag.y+(event.clientY-state.drag.startY)/state.scale;place(record);drawEdges()});node.addEventListener('pointerup',()=>{if(!state.drag)return;localStorage.setItem('hivelet:flow:'+item.key,JSON.stringify(record.position));state.drag=null});node.addEventListener('click',()=>inspect(record.item))}record.item=item;record.node.className='node '+type+(item.activeRequests?' active':'');record.node.innerHTML=type==='module'?moduleHtml(item):endpointHtml(item);place(record);return record}
function escape(value){const span=document.createElement('span');span.textContent=String(value);return span.innerHTML}function place(record){record.node.style.transform='translate('+record.position.x+'px,'+record.position.y+'px)'}
function drawEdges(){edges.replaceChildren();if(!state.snapshot)return;state.snapshot.endpoints.forEach(endpoint=>{const from=state.nodes.get('module:'+endpoint.moduleName),to=state.nodes.get('endpoint:'+endpoint.moduleName+':'+endpoint.id);if(!from||!to)return;const x1=from.position.x+from.node.offsetWidth,y1=from.position.y+from.node.offsetHeight/2,x2=to.position.x,y2=to.position.y+to.node.offsetHeight/2,path=document.createElementNS('http://www.w3.org/2000/svg','path'),bend=Math.max(65,(x2-x1)/2);path.setAttribute('d','M'+x1+' '+y1+' C'+(x1+bend)+' '+y1+' '+(x2-bend)+' '+y2+' '+x2+' '+y2);path.setAttribute('class','edge '+(endpoint.activeRequests||Date.now()-Date.parse(endpoint.lastRequestAt||0)<1800?'live':''));edges.append(path)})}
function render(snapshot){state.snapshot=snapshot;const valid=new Set();snapshot.modules.forEach((module,moduleIndex)=>{const endpoints=snapshot.endpoints.filter(endpoint=>endpoint.moduleName===module.name),requests=endpoints.reduce((sum,item)=>sum+item.requests,0),requestsPerMinute=endpoints.reduce((sum,item)=>sum+item.requestsPerMinute,0),duration=endpoints.reduce((sum,item)=>sum+item.averageResponseTime*item.requests,0),item={...module,key:'module:'+module.name,requests,requestsPerMinute,averageResponseTime:requests?duration/requests:0};valid.add(item.key);nodeElement(item,'module',0,moduleIndex);endpoints.forEach((endpoint,index)=>{const item={...endpoint,key:'endpoint:'+module.name+':'+endpoint.id};valid.add(item.key);nodeElement(item,'endpoint',index,moduleIndex)})});for(const [key,record] of state.nodes)if(!valid.has(key)){record.node.remove();state.nodes.delete(key)}el('empty').hidden=state.nodes.size>0;el('modules').textContent=snapshot.stats.activeModules;el('endpoints').textContent=snapshot.endpoints.length;el('rpm').textContent=snapshot.stats.requestsPerMinute;el('latency').textContent=fmt(snapshot.stats.averageResponseTime)+' ms';el('errors').textContent=(snapshot.stats.errorRate*100).toFixed(1)+'%';drawEdges();if(!state.fitted&&state.nodes.size){state.fitted=true;requestAnimationFrame(fitFlow)}}
function inspect(item){document.querySelectorAll('.node.selected').forEach(node=>node.classList.remove('selected'));state.nodes.get(item.key)?.node.classList.add('selected');el('inspector').hidden=false;el('inspect-label').textContent=item.method?'Endpoint telemetry':'Module details';el('inspect-title').textContent=item.method?item.method+' '+item.path:item.name+' v'+item.version;const rows=item.method?[['Version',item.version],['Module',item.moduleName],['Route ID',item.id],['Total requests',item.requests],['Requests / min',item.requestsPerMinute],['Error rate',(item.errorRate*100).toFixed(1)+'%'],['Average',fmt(item.averageResponseTime)+' ms'],['P95',fmt(item.p95ResponseTime)+' ms'],['Maximum',fmt(item.maxResponseTime)+' ms']]:[['Version',item.version],['Status',item.status],['Endpoints',item.routeCount],['Total requests',item.requests],['Requests / min',item.requestsPerMinute],['Loaded at',new Date(item.loadedAt).toLocaleString()]];el('details').innerHTML=rows.map(row=>'<div class="detail"><span>'+escape(row[0])+'</span><b>'+escape(row[1])+'</b></div>').join('')}
async function sync(){clearTimeout(state.timer);try{const response=await fetch('/api/state',{cache:'no-store'});if(response.status===401)return location.replace('/');if(!response.ok)throw Error();render(await response.json());el('connection').textContent='live'}catch{el('connection').textContent='offline'}finally{if(!document.hidden)state.timer=setTimeout(sync,refresh)}}
flow.addEventListener('pointerdown',event=>{if(event.target.closest('.node'))return;flow.setPointerCapture(event.pointerId);state.pan={x:event.clientX,y:event.clientY,startX:state.x,startY:state.y}});flow.addEventListener('pointermove',event=>{if(!state.pan)return;state.x=state.pan.startX+event.clientX-state.pan.x;state.y=state.pan.startY+event.clientY-state.pan.y;transform()});flow.addEventListener('pointerup',()=>state.pan=null);flow.addEventListener('wheel',event=>{event.preventDefault();const previous=state.scale,next=Math.min(1.8,Math.max(.3,previous*Math.exp(-event.deltaY*.001)));state.x=event.clientX-(event.clientX-state.x)*(next/previous);state.y=event.clientY-(event.clientY-state.y)*(next/previous);state.scale=next;transform()},{passive:false});
function zoom(factor){state.scale=Math.min(1.8,Math.max(.3,state.scale*factor));transform()}function fitFlow(){let width=1,height=1;state.nodes.forEach(record=>{width=Math.max(width,record.position.x+record.node.offsetWidth);height=Math.max(height,record.position.y+record.node.offsetHeight)});state.scale=Math.min(1,Math.max(.3,Math.min((innerWidth-80)/width,(innerHeight-120)/height)));state.x=32;state.y=64;transform()}el('zoom-in').onclick=()=>zoom(1.2);el('zoom-out').onclick=()=>zoom(.8);el('fit').onclick=fitFlow;el('logout').onclick=async()=>{await fetch('/api/logout',{method:'POST'});location.replace('/')};document.addEventListener('visibilitychange',()=>{clearTimeout(state.timer);if(!document.hidden)sync()});transform();sync();
</script></body></html>`;
}
